### PR TITLE
Add support for Google service accounts.

### PR DESCRIPTION
**Pull request by zub2**
This implements token request as described in https://developers.google.com/identity/protocols/OAuth2ServiceAccount#authorizingrequests

This behavior is triggered by using the option 'service' in createXOAuth2Generator(). See
README.md for more info.

### CODE REVIEW

**Comment by andris9** [comment]
I like the idea but I do not like too much the jsonwebtoken dependency as it adds 5MB and 30 sub-dependencies to this very simple and small module. Is there another way to sign the request or is the jsonwebtoken module the only way to do it?

**Comment by zub2** [comment]
I replaced the jsonwebtoken by a piece of code that is using the standard crypto module, basically following what https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatingjwt says.

I'm no crypto guru. But the risk there is hopefully low. It's just signing, not verifying.

I tested the result with my setup (sending email via gmail) and it works.

**Comment by zub2** [comment]
Ping. Are there any other issues with the pull request? I'd like to see it integrated.

**Comment by andris9** [comment]
Sorry, went unnoticed

**Comment by zub2** [comment]
Thanks!

**Pull request merged**
